### ISSUE TITLE
cannot load such file -- rack/handler (LoadError)

### ISSUE THREAD

**Issue by toqeer786** [systemed/tilemaker#450]
i want to serve  tiles using the demonstration server but when i run this command in server directory 

-  "sudo ruby server.rb /media/tilemaker-master/pakistan.mbtiles" 

  i have the following error 
ERROR
 "Starting local server
Traceback (most recent call last):
	3: from server.rb:22:in `<main>'
	2: from server.rb:118:in `<class:MapServer>'
	1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- rack/handler (LoadError)
 " 
 can you tell me what i missed here and how i can solved this error?

**Comment by toqeer786** [comment]
> Same problem, slightly different error:
> 
> ```
> Starting local server
> <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- rack/handler (LoadError)
>         from <internal:/usr/share/rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
>         from server.rb:118:in `<class:MapServer>'
>         from server.rb:22:in `<main>'
> ```
> 
> Command:
> 
> ```
> ruby server.rb ../poland-latest.mbtiles
> ```

i had solved this problem its simple if this error occured you have to install  ruby-rack deb package simply by just one line command : sudo apt-get install ruby-rack 
and then run again it will  start working ,
note: i am using ubuntu 20.04
